name: Trigger Quartz Build

on:
  push:
    branches:
      - main  # 或者您的默认分支名称

jobs:
  trigger-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Trigger my-notes workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.TRIGGER_TOKEN }}" \
            https://api.github.com/repos/summerKK/my-notes/actions/workflows/sync-and-deploy.yml/dispatches \
            -d '{"ref":"v4"}'
